// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestesAutomatizados.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MaiorEMenorProdutoPorPrecoNoCarrinhoDeComprasFeature : object, Xunit.IClassFixture<MaiorEMenorProdutoPorPrecoNoCarrinhoDeComprasFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MaiorMenorProduto.feature"
#line hidden
        
        public MaiorEMenorProdutoPorPrecoNoCarrinhoDeComprasFeature(MaiorEMenorProdutoPorPrecoNoCarrinhoDeComprasFeature.FixtureData fixtureData, TestesAutomatizados_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Tests/features", "Maior e Menor Produto por Preço no Carrinho de Compras", "  Como um cliente interessado em tomar decisões com base no preço dos produtos\n  " +
                    "Eu quero ser capaz de identificar o maior e o menor produto no meu carrinho de c" +
                    "ompras\n  Para tomar decisões informadas de compra", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Identificar o maior e o menor produto por preço no carrinho de compras")]
        [Xunit.TraitAttribute("FeatureTitle", "Maior e Menor Produto por Preço no Carrinho de Compras")]
        [Xunit.TraitAttribute("Description", "Identificar o maior e o menor produto por preço no carrinho de compras")]
        public void IdentificarOMaiorEOMenorProdutoPorPrecoNoCarrinhoDeCompras()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Identificar o maior e o menor produto por preço no carrinho de compras", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("Eu adicionei alguns produtos ao meu carrinho de compras", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
    testRunner.When("Eu seleciono a opção para identificar o maior e o menor produto por preço no carr" +
                        "inho de compras", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
    testRunner.Then("Devo ver as informações do produto mais caro e mais barato no meu carrinho de com" +
                        "pras", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 12
    testRunner.And("Eu devo ver o maior produto exibido primeiro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 13
    testRunner.And("Eu devo ver o menor produto exibido depois do maior produto", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                MaiorEMenorProdutoPorPrecoNoCarrinhoDeComprasFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                MaiorEMenorProdutoPorPrecoNoCarrinhoDeComprasFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
